FROM python:3.13-slim-trixie

COPY --from=ghcr.io/astral-sh/uv:0.10.7 /uv /uvx /bin/

ENV UV_NO_DEV=1
ENV PYTHONUNBUFFERED=1

# Add code location code
WORKDIR /opt/dagster/app

COPY dagster/premierlytics-dagster/pyproject.toml /opt/dagster/app/pyproject.toml
COPY dagster/premierlytics-dagster/uv.lock /opt/dagster/app/uv.lock
COPY dagster/premierlytics-dagster/src /opt/dagster/app/src

ENV PYTHONPATH=/opt/dagster/app/src

# Create venv and install dependencies
RUN uv venv /opt/dagster/app/.venv
ENV PATH="/opt/dagster/app/.venv/bin:$PATH"
RUN uv pip install --system -e ".[dev]"

# RUN uv sync --locked --bin-dir /usr/local/bin

RUN pip install dbt-duckdb dagster-dbt
COPY premierlytics_dbt /opt/dagster/dbt
COPY dagster/premierlytics-dagster/src/premierlytics_dagster/defs/dbt/profiles.yml /opt/dagster/dbt/profiles.yml
RUN cd /opt/dagster/dbt && dbt deps && dbt parse

# Run dagster code server on port 4000
EXPOSE 4000

# Healthcheck for Dagster gRPC server
HEALTHCHECK \
    --timeout=1s \
    --start-period=5s \
    --interval=5s \
    --retries=20 \
    CMD ["dagster", "api", "grpc-health-check", "-p", "4000"]

# Run Dagster user code gRPC server
CMD [ "dagster","api", "grpc", "-h", "0.0.0.0", "-p", "4000","-m", "premierlytics_dagster.definitions"]