
services:
  docker_postgres:
    image: postgres:13
    container_name: docker_postgres
    env_file:
      - ../.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - premierlytics_nw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 8s
      retries: 5
  
  dagster_user_code:
    build:
      context: ..
      dockerfile: ./docker/dagster/Dockerfile_user_code
    container_name: dagster_user_code
    image: dagster_user_code_image
    volumes:
      - duckdb_data:/data/duckdb
      - ../dagster/premierlytics-dagster/src:/opt/dagster/app/src
      - ../premierlytics_dbt:/opt/dagster/dbt
    restart: always
    env_file:
      - ../.env.dev
    networks:
      - premierlytics_nw
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 4000 || exit 1"]
      interval: 40s
      timeout: 10s
      retries: 3

  dagster_webserver:
    build:
      context: ..
      dockerfile: ./docker/dagster/Dockerfile_dagster
    entrypoint:
      - dagster-webserver
      - -h
      - '0.0.0.0'
      - -p
      - '3000'
      - -w
      - workspace.yaml
    container_name: dagster_webserver
    expose:
      - '3000'
    ports:
      - '3000:3000'
    env_file:
      - ../.env.dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dagster_io:/tmp/io_manager_storage
      - dagster_storage:/opt/dagster/storage
      - dagster_compute_logs:/opt/dagster/compute_logs
    networks:
      - premierlytics_nw
    depends_on:
      docker_postgres:
        condition: service_healthy
      dagster_user_code:
        condition: service_healthy
  
  dagster_daemon:
    build:
      context: ..
      dockerfile: ./docker/dagster/Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    restart: on-failure
    env_file:
      - ../.env.dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dagster_io:/tmp/io_manager_storage
      - dagster_storage:/opt/dagster/storage
      - dagster_compute_logs:/opt/dagster/compute_logs
    networks:
      - premierlytics_nw
    depends_on:
      docker_postgres:
        condition: service_healthy
      dagster_user_code:
        condition: service_started

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ':9001'
    env_file:
      - ../.env.dev
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - premierlytics_nw
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio_init:
    image: minio/mc
    container_name: minio_init
    env_file:
      - ../.env.dev
    networks:
      - premierlytics_nw
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set maestro http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      mc mb --ignore-existing maestro/premierlytics-dev-bucket;
      exit 0;
      "
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - duckdb_data:/data/duckdb
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - premierlytics_nw
    depends_on:
      - duckdb_init
      - dagster_user_code
  
  duckdb_init:
    image: python:3.11-slim
    user: root
    volumes:
      - duckdb_data:/data/duckdb
      - ./duckdb/duckdb_init.py:/app/duckdb_init.py
    command: bash -c "pip install duckdb --quiet && python /app/duckdb_init.py"
    networks:
      - premierlytics_nw

networks:
  premierlytics_nw:
    driver: bridge
    name: premierlytics_nw

volumes:
  postgres_data:
  minio_data:
  dagster_io:
  dagster_storage:
  dagster_compute_logs:
  duckdb_data:
  metabase_data:
  cloudbeaver_data: