with source as (
    select * from {{ source('premierlytics', 'playermatchstats_bronze') }}
),

cleaned as (
    select
        player_id,
        match_id,
        minutes_played,
        goals,
        assists,
        total_shots,
        xg,
        xa,
        xgot,
        shots_on_target,
        successful_dribbles,
        big_chances_missed,
        touches_opposition_box,
        touches,
        accurate_passes,
        chances_created,
        final_third_passes,
        accurate_crosses,
        accurate_long_balls,
        tackles_won,
        interceptions,
        recoveries,
        blocks,
        clearances,
        headed_clearances,
        dribbled_past,
        duels_won,
        duels_lost,
        ground_duels_won,
        aerial_duels_won,
        was_fouled,
        fouls_committed,
        saves,
        goals_conceded,
        xgot_faced,
        goals_prevented,
        sweeper_actions,
        gk_accurate_passes,
        gk_accurate_long_balls,
        offsides,
        high_claim,
        tackles,
        accurate_passes_percent,
        accurate_crosses_percent,
        accurate_long_balls_percent,
        ground_duels_won_percent,
        aerial_duels_won_percent,
        successful_dribbles_percent,
        tackles_won_percent,
        start_min,
        finish_min,
        team_goals_conceded,
        penalties_scored,
        penalties_missed,
        dispossessed,
        corners,
        saves_inside_box,
        top_speed,
        distance_covered,
        walking_distance,
        running_distance,
        sprinting_distance,
        number_of_sprints,
        defensive_contributions,
        ingested_at
    from source    
)

select * from cleaned