with source as (
    select * from {{ source('premierlytics', 'fixtures_bronze') }}
),

cleaned as (
    select
        gameweek,
        season,
        match_id,
        match_url,
        fotmob_id,
        kickoff_time,
        tournament,
        finished as is_finished,
        stats_processed as is_stats_processed,
        player_stats_processed as is_player_stats_processed,
        home_team,
        away_team,
        home_team_elo,
        away_team_elo,
        home_score,
        away_score,
        home_possession,
        away_possession,
        home_expected_goals_xg,
        away_expected_goals_xg,
        home_xg_open_play,
        away_xg_open_play,
        home_xg_set_play,
        away_xg_set_play,
        home_non_penalty_xg,
        away_non_penalty_xg,
        home_non_penalty_xg,
        away_non_penalty_xg,
        home_xg_on_target_xgot,
        away_xg_on_target_xgot,
        home_total_shots,
        away_total_shots,
        home_shots_on_target,
        away_shots_on_target,
        home_shots_off_target,
        away_shots_off_target,
        home_blocked_shots,
        away_blocked_shots,
        home_hit_woodwork,
        away_hit_woodwork,
        home_shots_inside_box,
        away_shots_inside_box,
        home_shots_inside_box,
        away_shots_inside_box,
        home_shots_outside_box,
        away_shots_outside_box,
        home_passes,
        away_passes,
        home_own_half,
        away_own_half,
        home_opposition_half,
        away_opposition_half,
        home_accurate_long_balls,
        away_accurate_long_balls,
        home_accurate_long_balls_pct,
        away_accurate_long_balls_pct,
        home_accurate_crosses,
        away_accurate_crosses,
        home_accurate_crosses_pct,
        away_accurate_crosses_pct,
        home_throws,
        away_throws,
        home_touches_in_opposition_box,
        away_touches_in_opposition_box,
        home_offsides,
        away_offsides,
        home_yellow_cards,
        away_yellow_cards,
        home_red_cards,
        away_red_cards,
        home_tackles_won,
        away_tackles_won,
        home_tackles_won_pct,
        away_tackles_won_pct,
        home_interceptions,
        away_interceptions,
        home_blocks,
        away_blocks,
        home_clearances,
        away_clearances,
        home_keeper_saves,
        away_keeper_saves,
        home_duels_won,
        away_duels_won,
        home_ground_duels_won,
        away_ground_duels_won,
        home_ground_duels_won_pct,
        away_ground_duels_won_pct,
        home_aerial_duels_won,
        away_aerial_duels_won,
        home_aerial_duels_won_pct,
        away_aerial_duels_won_pct,
        home_successful_dribbles,
        away_successful_dribbles,
        home_successful_dribbles_pct,
        away_successful_dribbles_pct,
        ingested_at
    from source
)


select * from cleaned