-- DDL for playerstats_bronze table

DROP TYPE IF EXISTS status_type;
CREATE TYPE status_type AS ENUM ('a', 'd', 'i', 'n', 's', 'u');

CREATE TABLE IF NOT EXISTS playerstats_bronze (
    id INTEGER NOT NULL,
    first_name VARCHAR,
    second_name VARCHAR,
    web_name VARCHAR,
    status status_type,
    gameweek INTEGER NOT NULL,
    season VARCHAR NOT NULL,
    chance_of_playing_next_round INTEGER, 
    chance_of_playing_this_round INTEGER, 
    now_cost DOUBLE,
    now_cost_rank INTEGER,
    now_cost_rank_type INTEGER,
    cost_change_event INTEGER NOT NULL,
    cost_change_event_fall DOUBLE,
    cost_change_start INTEGER,
    cost_change_start_fall DOUBLE,
    selected_by_percent DOUBLE NOT NULL,
    selected_rank INTEGER NOT NULL,
    selected_rank_type INTEGER,
    total_points INTEGER NOT NULL,
    event_points INTEGER NOT NULL,
    points_per_game DOUBLE,
    points_per_game_rank DOUBLE,
    points_per_game_rank_type DOUBLE,
    bonus INTEGER NOT NULL,
    bps INTEGER NOT NULL,
    form DOUBLE NOT NULL,
    form_rank DOUBLE,
    form_rank_type DOUBLE,
    value_form DOUBLE NOT NULL,
    value_season DOUBLE NOT NULL,
    dreamteam_count INTEGER,
    transfers_in INTEGER NOT NULL,
    transfers_in_event INTEGER NOT NULL,
    transfers_out INTEGER NOT NULL,
    transfers_out_event INTEGER NOT NULL,
    ep_next DOUBLE, 
    ep_this DOUBLE,
    expected_goals DOUBLE,
    expected_assists DOUBLE NOT NULL,
    expected_goal_involvements DOUBLE NOT NULL,
    expected_goals_conceded DOUBLE NOT NULL,
    expected_goals_per_90 DOUBLE,
    expected_assists_per_90 DOUBLE,
    expected_goal_involvements_per_90 DOUBLE,
    expected_goals_conceded_per_90 DOUBLE,
    influence DOUBLE NOT NULL,
    influence_rank INTEGER,
    influence_rank_type INTEGER,
    creativity DOUBLE NOT NULL,
    creativity_rank INTEGER,
    creativity_rank_type INTEGER,
    threat DOUBLE NOT NULL,
    threat_rank INTEGER,
    threat_rank_type INTEGER,
    ict_index DOUBLE NOT NULL,
    ict_index_rank INTEGER,
    ict_index_rank_type INTEGER,
    corners_and_indirect_freekicks_order INTEGER,
    corners_and_indirect_freekicks_text VARCHAR,
    direct_freekicks_order INTEGER, 
    direct_freekicks_text VARCHAR,
    penalties_order INTEGER,
    penalties_text VARCHAR,
    set_piece_threat DOUBLE,

    -- V2 columns
    news VARCHAR,
    news_added VARCHAR,
    minutes INTEGER,
    goals_scored INTEGER,
    assists INTEGER,
    clean_sheets INTEGER,
    goals_conceded INTEGER,
    own_goals INTEGER,
    penalties_saved INTEGER,
    penalties_missed INTEGER,
    yellow_cards INTEGER,
    red_cards INTEGER,
    saves INTEGER,
    starts INTEGER,
    defensive_contribution INTEGER,
    tackles INTEGER,
    clearances_blocks_interceptions INTEGER,
    recoveries INTEGER,
    saves_per_90 DOUBLE,
    clean_sheets_per_90 DOUBLE,
    goals_conceded_per_90 DOUBLE,
    starts_per_90 DOUBLE,
    defensive_contribution_per_90 DOUBLE,

    ingested_at TIMESTAMP NOT NULL,
)