-- DDL script for Matches Bronze Table
CREATE TABLE IF NOT EXISTS matches_bronze (
    gameweek    INTEGER NOT NULL,
    season      VARCHAR NOT NULL,
    kickoff_time TIMESTAMP NOT NULL,
    home_team   INTEGER NOT NULL,
    home_team_elo DOUBLE NOT NULL,
    home_score  INTEGER NOT NULL,
    away_score INTEGER NOT NULL,
    away_team   INTEGER NOT NULL,
    away_team_elo DOUBLE NOT NULL,
    finished    BOOLEAN NOT NULL,
    match_id    VARCHAR NOT NULL,
    match_url   VARCHAR NOT NULL,

    home_possession INTEGER,
    away_possession INTEGER,
    home_expected_goals_xg DOUBLE,
    away_expected_goals_xg DOUBLE,
    home_xg_open_play   DOUBLE,
    away_xg_open_play   DOUBLE,
    home_xg_set_play    DOUBLE,
    away_xg_set_play    DOUBLE,
    home_non_penalty_xg DOUBLE,
    away_non_penalty_xg DOUBLE,
    home_xg_on_target_xgot  DOUBLE,
    away_xg_on_target_xgot  DOUBLE,

    home_total_shots    INTEGER,
    away_total_shots    INTEGER,
    home_shots_on_target INTEGER,
    away_shots_on_target    INTEGER,
    home_shots_off_target   INTEGER,
    away_shots_off_target   INTEGER,
    home_blocked_shots  INTEGER,
    away_blocked_shots  INTEGER,
    home_shots_inside_box   INTEGER,
    away_shots_inside_box   INTEGER,
    home_shots_outside_box  INTEGER,
    away_shots_outside_box  INTEGER,
    home_big_chances    INTEGER,
    away_big_chances    INTEGER,
    home_big_chances_missed INTEGER,
    away_big_chances_missed INTEGER,
    home_hit_woodwork   INTEGER,
    away_hit_woodwork   INTEGER,

    home_passes INTEGER,
    away_passes INTEGER,
    home_accurate_passes    INTEGER,
    away_accurate_passes    INTEGER,
    home_accurate_passes_pct    INTEGER,
    away_accurate_passes_pct    INTEGER,
    home_own_half   INTEGER,
    away_own_half   INTEGER,
    home_opposition_half    INTEGER,
    away_opposition_half    INTEGER,
    home_accurate_long_balls    INTEGER,
    away_accurate_long_balls    INTEGER,
    home_accurate_long_balls_pct    INTEGER,
    away_accurate_long_balls_pct    INTEGER,
    home_accurate_crosses   INTEGER,
    away_accurate_crosses   INTEGER,
    home_accurate_crosses_pct INTEGER,
    away_accurate_crosses_pct INTEGER,

    home_corners INTEGER,
    away_corners INTEGER,
    home_throws INTEGER,
    away_throws INTEGER,
    home_fouls_committed INTEGER,
    away_fouls_committed INTEGER,
    home_offsides INTEGER,
    away_offsides INTEGER,
    home_yellow_cards INTEGER,
    away_yellow_cards INTEGER,
    home_red_cards INTEGER,
    away_red_cards INTEGER,
    home_touches_in_opposition_box INTEGER,
    away_touches_in_opposition_box INTEGER,

    home_tackles_won INTEGER,
    away_tackles_won INTEGER,
    home_tackles_won_pct INTEGER,
    away_tackles_won_pct INTEGER,
    home_interceptions INTEGER,
    away_interceptions INTEGER,
    home_blocks INTEGER,
    away_blocks INTEGER,
    home_clearances INTEGER,
    away_clearances INTEGER,
    home_keeper_saves INTEGER,
    away_keeper_saves INTEGER,

    home_duels_won INTEGER,
    away_duels_won INTEGER,
    home_ground_duels_won INTEGER,
    away_ground_duels_won INTEGER,
    home_ground_duels_won_pct INTEGER,
    away_ground_duels_won_pct INTEGER,
    home_aerial_duels_won INTEGER,
    away_aerial_duels_won INTEGER,
    home_aerial_duels_won_pct INTEGER,
    away_aerial_duels_won_pct INTEGER,

    home_successful_dribbles INTEGER,
    away_successful_dribbles INTEGER,
    home_successful_dribbles_pct INTEGER,
    away_successful_dribbles_pct INTEGER,

    fotmob_id INTEGER,
    stats_processed BOOLEAN,
    player_stats_processed BOOLEAN,

    tournament VARCHAR ,
    away_distance_covered INTEGER,
    home_distance_covered INTEGER,
    home_walking_distance INTEGER,
    away_walking_distance INTEGER,
    home_running_distance INTEGER,
    away_running_distance INTEGER,
    home_sprinting_distance INTEGER,
    away_sprinting_distance INTEGER,
    home_number_of_sprints INTEGER,
    away_number_of_sprints INTEGER,
    home_top_speed DOUBLE,
    away_top_speed DOUBLE,

    ingested_at TIMESTAMP NOT NULL,

    PRIMARY KEY (match_id)
)