-- DDL for playermatchstats_bronze table

CREATE TABLE IF NOT EXISTS playermatchstats_bronze (
    playermatchstats_id UUID DEFAULT gen_random_uuid(),
    player_id INTEGER NOT NULL,
    season VARCHAR NOT NULL,
    gameweek INT NOT NULL,
    match_id VARCHAR NOT NULL,
    minutes_played INTEGER NOT NULL,
    goals INTEGER NOT NULL,
    assists INTEGER NOT NULL,
    total_shots INTEGER NOT NULL,
    xg DOUBLE NOT NULL,
    xa DOUBLE NOT NULL,
    xgot DOUBLE NOT NULL,
    shots_on_target INTEGER NOT NULL,
    successful_dribbles INTEGER NOT NULL,
    big_chances_missed INTEGER NOT NULL,
    touches_opposition_box INTEGER NOT NULL,
    touches INTEGER NOT NULL,
    accurate_passes INTEGER NOT NULL,
    chances_created INTEGER NOT NULL,
    final_third_passes INTEGER NOT NULL,
    accurate_crosses INTEGER NOT NULL,
    accurate_long_balls INTEGER NOT NULL,
    tackles_won INTEGER NOT NULL,
    interceptions INTEGER NOT NULL,
    recoveries INTEGER NOT NULL,
    blocks INTEGER NOT NULL,
    clearances INTEGER NOT NULL,
    headed_clearances INTEGER NOT NULL,
    dribbled_past INTEGER NOT NULL,
    duels_won INTEGER NOT NULL,
    duels_lost INTEGER NOT NULL,
    ground_duels_won INTEGER NOT NULL,
    aerial_duels_won INTEGER NOT NULL,
    was_fouled INTEGER NOT NULL,
    fouls_committed INTEGER NOT NULL,

    saves INTEGER NOT NULL,
    goals_conceded INTEGER NOT NULL, 
    xgot_faced DOUBLE NOT NULL,
    goals_prevented DOUBLE NOT NULL, 
    sweeper_actions INTEGER NOT NULL, 
    gk_accurate_passes INTEGER NOT NULL, 
    gk_accurate_long_balls INTEGER NOT NULL, 

    offsides INTEGER NOT NULL,
    high_claim INTEGER NOT NULL,
    tackles INTEGER NOT NULL,

    accurate_passes_percent DOUBLE NOT NULL,
    accurate_crosses_percent DOUBLE NOT NULL, 
    accurate_long_balls_percent DOUBLE NOT NULL, 
    ground_duels_won_percent DOUBLE NOT NULL,
    aerial_duels_won_percent DOUBLE NOT NULL,
    successful_dribbles_percent DOUBLE NOT NULL, 
    tackles_won_percent DOUBLE NOT NULL,

    start_min INTEGER NOT NULL,
    finish_min INTEGER NOT NULL,
    team_goals_conceded INTEGER NOT NULL,
    penalties_scored INTEGER NOT NULL,
    penalties_missed INTEGER NOT NULL,

    -- V2 additional rows
    dispossessed DOUBLE,
    corners INTEGER,
    saves_inside_box INTEGER,
    top_speed DOUBLE,
    distance_covered DOUBLE,
    walking_distance DOUBLE,
    running_distance DOUBLE,
    sprinting_distance DOUBLE,
    number_of_sprints DOUBLE,
    defensive_contributions DOUBLE,

    ingested_at TIMESTAMP NOT NULL,

    PRIMARY KEY (playermatchstats_id)
)