# config/seasons.yaml

seasons:
  "2024-2025":
    matches:
      path_pattern: "matches/GW{gw}/matches.csv"
      model_version: "v1"
    playermatchstats:
      path_pattern: "playermatchstats/GW{gw}/playermatchstats.csv"
      model_version: "v1"
    players:
      path_pattern: "players/players.csv"
      model_version: "v1"
    playerstats:
      path_pattern: "playerstats/playerstats.csv"
      model_version: "v1"
    teams:
      path_pattern: "teams/teams.csv"
      model_version: "v1"
  "2025-2026":
    fixtures:
      path_pattern: "By Gameweek/GW{gw}/fixtures.csv"
      model_version: "v1"
    matches:
      path_pattern: "By Gameweek/GW{gw}/matches.csv"
      model_version: "v2"
    player_gameweek_stats:
      path_pattern: "By Gameweek/GW{gw}/player_gameweek_stats.csv"
      model_version: "v1"
    playermatchstats:
      path_pattern: "By Gameweek/GW{gw}/playermatchstats.csv"
      model_version: "v2"
    players:
      path_pattern: "By Gameweek/GW{gw}/players.csv"
      model_version: "v2"
    playerstats:
      path_pattern: "By Gameweek/GW{gw}/playerstats.csv"
      model_version: "v2"
    teams:
      path_pattern: "By Gameweek/GW{gw}/teams.csv"
      model_version: "v2"